---
- name: setup development environment
  include_tasks:
    file: dev-tools.yml
    apply:
      tags:
        - install
  tags:
    - install

- name: pre-requisites for enabled features
  include_tasks:
    file: features/main.yml
    apply:
      tags:
        - install
  tags:
    - install

- name: installation
  include_tasks:
    file: install.yml
    apply:
      tags:
        - install
  tags:
    - install

- name: configure pmacctd
  include_tasks:
    file: configure.yml
    apply:
      tags:
        - configure
  tags:
    - configure
