- name: check jansson lib exist status
  stat:
    path: "{{jansson_lib_path}}"
  register: jansson 

- name: compile and install jansson devel
  include_tasks: jansson.yml
  when: not jansson.stat.exists

- name: add kafka enable flags
  set_fact:
    config_params: "{{config_params}} --enable-kafka --enable-jansson"

- name: install kafka devel
  package:
    name: 
    - librdkafka-dev
    state: present

- name: install jansson
  debug:
    msg: install jansson
